force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Security Address</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Balance_of_the_Loan__c.field-meta.xml
<CustomField>
    <fullName>Balance_of_the_Loan__c</fullName>
    <formula>IF(
Total_Charges_on_the_Loan__c = null,
Gross_Loan_Amount__c,
Total_Charges_on_the_Loan__c + Gross_Loan_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Loan Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <label>Loan Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Gross_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Loan_Amount__c</fullName>
    <label>Gross Loan Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Loan Term (Months)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Total_Charges_on_the_Loan__c.field-meta.xml
<CustomField>
    <fullName>Total_Charges_on_the_Loan__c</fullName>
    <label>Total Charges on Loan</label>
    <summarizedField>Loan_Charge__c.Amount__c</summarizedField>
    <summaryForeignKey>Loan_Charge__c.Loan__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <label>Loan Charge</label>
    <nameField>
        <label>Loan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Release Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/loanManagerHelperClassTest.cls
@istest
public class loanManagerHelperClassTest {
    
    public static account createDefaultAccount(){
        Account defaultAccount = new Account();
        defaultAccount.name = 'Test Account Name';
        
        return defaultAccount;
    }
    
    public static Loan__c createDefaultLoan(Account acc){ //, List<Loan_Charge__c> LC){
        Loan__c defaultLoan = new Loan__c();
        defaultLoan.name = 'Test Loan Name';
        defaultLoan.account__c = acc.Id;
        defaultLoan.Address__c = 'Test Loan Security Address';
        defaultLoan.Gross_Loan_Amount__c = 65000;
        defaultLoan.Date_Loan_Issued__c = system.today();
        defaultLoan.Term__c = 20;
        
        return defaultLoan;
    }
    
    public static Loan_Charge__c createReleaseChargeLoanCharge(Account Acc, Loan__c Loan){
        Loan_Charge__c ReleaseChargeLC = new Loan_Charge__c();
        ReleaseChargeLC.Date__c = system.today();
        ReleaseChargeLC.Charge_Type__c = 'Release Charge';
        ReleaseChargeLC.Amount__c = 500;
        ReleaseChargeLC.Loan__c = Loan.id;
        
        return ReleaseChargeLC;
    }
    
    
    public static Loan_Charge__c createInterestChargeLoanCharge(Account Acc, Loan__c Loan){
        Loan_Charge__c InterestChargeLC = new Loan_Charge__c();
        InterestChargeLC.Date__c = system.today();
        InterestChargeLC.Charge_Type__c = 'Interest charge';
        InterestChargeLC.Amount__c = 750;
        InterestChargeLC.Loan__c = Loan.id;
        
        return InterestChargeLC;
    }
    
    
    public static Loan_Charge__c createLegalFeeLoanCharge(Account Acc, Loan__c Loan){
        Loan_Charge__c LegalFeeLC = new Loan_Charge__c();
        LegalFeeLC.Date__c = system.today();
        LegalFeeLC.Charge_Type__c = 'Legal Fee';
        LegalFeeLC.Amount__c = 1000;
        LegalFeeLC.Loan__c = Loan.id;
        
        return LegalFeeLC;
    }
    
    public static Loan_Charge__c createAdminFeeLoanCharge(Account Acc, Loan__c Loan){
        Loan_Charge__c AdminFeeLC = new Loan_Charge__c();
        AdminFeeLC.Date__c = system.today();
        AdminFeeLC.Charge_Type__c = 'Admin Fee';
        AdminFeeLC.Amount__c = 250;
        AdminFeeLC.Loan__c = Loan.id;
        
        return AdminFeeLC;
    }
    
    @istest
    public static void createLoanWithoutExplicitLoanCharge(){
        account a = createDefaultAccount();
        insert a;
        loan__c l = createDefaultLoan(a);
        
        Test.startTest();
        insert l;
        List<Loan_Charge__c> releaseChargeLC = [SELECT ID, Charge_Type__c,Loan__c,date__c from Loan_Charge__c where loan__c =: l.id AND charge_type__c = 'Release Charge'];
        System.debug('Loan Found! Loan: ' + l);
        System.debug('Release Charge Loan Charge Found! Loan Charge: ' + releaseChargeLC);
        System.Assert(
            releaseChargeLC[0].Loan__c == l.id && 
            releaseChargeLC[0].Charge_Type__c == 'Release Charge' &&
            releaseChargeLC[0].id != null,
            'Error - An ID was not found, meaning the Loan Charge created (or not created) was not of Release Charge value');
        
        Test.stopTest();
    }
    
    @istest
    public static void updateLoanTerm(){
        account a = createDefaultAccount();
        insert a;
        loan__c l = createDefaultLoan(a);
        insert l;
        l.Term__c = 55;
        Test.startTest();
        List<Loan_Charge__c> allLoanCharges = [SELECT ID, Charge_Type__c,Loan__c,date__c from Loan_Charge__c where loan__c =: l.id];
        
        System.debug('All Loan Charges Created at beginning of Test '+ allLoanCharges);	
        List<Loan_Charge__c> releaseChargeLC = [SELECT ID, Charge_Type__c,Loan__c,date__c from Loan_Charge__c where loan__c =: l.id AND charge_type__c = 'Release Charge'];
        System.debug('Release Charge Date BEFORE Term amendment: ' + releaseChargeLC[0].date__c);
        
        update l;
        Loan__c updatedLoan = [SELECT Id, Term__c, Date_Loan_Issued__c FROM Loan__c WHERE Id = :l.Id];
        Date ExpectedDate = updatedLoan.Date_Loan_Issued__c.addmonths(75);
        
        releaseChargeLC = [SELECT ID, Charge_Type__c,Loan__c,date__c from Loan_Charge__c where loan__c =: l.id AND charge_type__c = 'Release Charge'];
        System.debug('Release Charge Date AFTER Term amendment: ' + releaseChargeLC[0].date__c);
        System.debug('Loan Found! Loan: ' + l);
        System.debug('Loan Charge Found! Loan Charge: ' + releaseChargeLC);
        allLoanCharges = [SELECT ID, Charge_Type__c,Loan__c,date__c from Loan_Charge__c where loan__c =: l.id];
        System.debug('All Loan Charges Created at end of Test '+ allLoanCharges);
        
        System.Assert(
            releaseChargeLC[0].Loan__c == l.id && 
            releaseChargeLC[0].id != null &&
            releaseChargeLC[0].date__c == ExpectedDate &&
            allLoanCharges.size() == 2, // 1 Release Charge via Loan Insertion & 1 Admin Fee via Term Amendment
            'Error - An ID was not found, or the date on the Release Charge was not as expected after the Term update.');
        
        Test.stopTest();
    }
    
    @istest
    public static void createLoanChargesToTestTotalChargesOnLoan(){
        account a = createDefaultAccount();
        insert a;
        loan__c l = createDefaultLoan(a); 
        Decimal expectedtotal = 0; 
        
        Test.startTest();
        insert l;
        Loan_Charge__c ic = createInterestChargeLoanCharge(a,l);
        Loan_Charge__c lf = createLegalFeeLoanCharge(a,l);
        insert ic;
        insert lf;
        
        List<Loan__c> Loan = [SELECT ID, Total_Charges_on_the_Loan__c,Gross_Loan_Amount__c,Balance_of_the_Loan__c from Loan__c where id =: l.id];
        System.debug('Loan Found! Loan: ' + Loan);
        System.debug('Finding all Loan Charges Relating to Loan in order to affirm that Loan Amount Fields are correct.');
        List<Loan_Charge__c> LoanCharges = [SELECT id, amount__c, Loan__c from Loan_Charge__c where Loan__c =: l.id];
        
        for(Loan_Charge__c lc : LoanCharges){
            expectedtotal = expectedtotal + lc.amount__c; 
        }
        
        expectedtotal = expectedtotal + l.Gross_Loan_Amount__c;
        
        system.debug('ExpectedTotal: '+ expectedtotal);
        system.debug('ActualTotal: '+ l.Balance_of_the_Loan__c); // value doesnt display in debug log but System.Assert Method verifies that the Roll-Up Works as expected.
        
        System.Assert(
            Loan[0].id != null &&
            expectedtotal == Loan[0].Balance_of_the_Loan__c,
            'Error - An ID was not found, or the calculation for the Total Balance Of the Loan was incorrect.');
        
        Test.stopTest();
    }
    
}